// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrMuaFRywNzQQ2mldZBa407YtteP72md8',
    appId: '1:250493326515:web:5829a9273346bc967e8cc6',
    messagingSenderId: '250493326515',
    projectId: 'durugol-cicekleri',
    authDomain: 'durugol-cicekleri.firebaseapp.com',
    storageBucket: 'durugol-cicekleri.firebasestorage.app',
    measurementId: 'G-X8VHBY1MZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcLbHaKNTuDOJy98KE4KqGZ40Z-Fyu7ns',
    appId: '1:250493326515:android:e39e75c28f0caf2b7e8cc6',
    messagingSenderId: '250493326515',
    projectId: 'durugol-cicekleri',
    storageBucket: 'durugol-cicekleri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAznABDJEXxaJ8JExFPK8CtPOnahW8VSkU',
    appId: '1:250493326515:ios:2d091d7c1d6320377e8cc6',
    messagingSenderId: '250493326515',
    projectId: 'durugol-cicekleri',
    storageBucket: 'durugol-cicekleri.firebasestorage.app',
    iosBundleId: 'com.example.durugolCicekleri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAznABDJEXxaJ8JExFPK8CtPOnahW8VSkU',
    appId: '1:250493326515:ios:2d091d7c1d6320377e8cc6',
    messagingSenderId: '250493326515',
    projectId: 'durugol-cicekleri',
    storageBucket: 'durugol-cicekleri.firebasestorage.app',
    iosBundleId: 'com.example.durugolCicekleri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrMuaFRywNzQQ2mldZBa407YtteP72md8',
    appId: '1:250493326515:web:42c9ce9f4d0d06ce7e8cc6',
    messagingSenderId: '250493326515',
    projectId: 'durugol-cicekleri',
    authDomain: 'durugol-cicekleri.firebaseapp.com',
    storageBucket: 'durugol-cicekleri.firebasestorage.app',
    measurementId: 'G-FYFM6G8WMH',
  );
}
